Make sure each Compositor::IDisplay::Instance() call is Released()
WebPlatformForEmbedded/WPEBackend-rdk pull request #109
Opened 2024-10-03 11:59 UTC by VeithMetro

2024-10-03 12:17 UTC, sebaszm approved these changes

2024-10-08 10:23 UTC, pwielders commented on src/thunder/renderer-backend.cpp
> +            Thunder::Compositor::IDisplay* display = static_cast<Thunder::Compositor::IDisplay*>(data);
This is against the rules of reference counting. You get the interface offered, so the on offering you this interface has to have a Reference count. You do not maintain the interface and thus correctly do not do an AddRef (or QueryInterface) on this interface and thus you should not Release it as now you are releasing on beha;f of someone else...

2024-10-08 10:26 UTC, pwielders commented on src/thunder/renderer-backend.cpp
> -        return Thunder::Compositor::IDisplay::Instance(Thunder::DisplayName())->Native();
I think that this was your leak, that you where trying to solve above, cause the method Thunder::Compositor::IDisplay::Instance(Thunder::DisplayName()) returns a reference counted interface to the callee and the callee is now responsible to Release. By now using the data, the release is no needed, see discussion above..

2024-10-08 10:27 UTC, pwielders requested changes
It is causing to many Releases now or it is fixed in the wrong spot..

2024-10-08 13:24 UTC, pwielders approved these changes
Love it!

2024-10-08 13:24 UTC, merged